// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgfIGFdNM2tY-BEoq5GKuajNDg5iw44b8',
    appId: '1:386955907787:web:f88762583148326853414e',
    messagingSenderId: '386955907787',
    projectId: 'noorvia-3a12e',
    authDomain: 'noorvia-3a12e.firebaseapp.com',
    storageBucket: 'noorvia-3a12e.firebasestorage.app',
    measurementId: 'G-8E714HBZ6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhNISkwjrTNAYqoIsWDt4A2brHPhjRPWg',
    appId: '1:386955907787:android:076d39c65c79343853414e',
    messagingSenderId: '386955907787',
    projectId: 'noorvia-3a12e',
    storageBucket: 'noorvia-3a12e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCJMnLNeDLkH-cTXxiUhcagl77sHusI1U',
    appId: '1:386955907787:ios:9f2b7538bf1e8b8353414e',
    messagingSenderId: '386955907787',
    projectId: 'noorvia-3a12e',
    storageBucket: 'noorvia-3a12e.firebasestorage.app',
    iosClientId: '386955907787-60qcmr88pq6vshl63ha54hq6ss0babm9.apps.googleusercontent.com',
    iosBundleId: 'com.butterflydevs.noorvia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCJMnLNeDLkH-cTXxiUhcagl77sHusI1U',
    appId: '1:386955907787:ios:9f2b7538bf1e8b8353414e',
    messagingSenderId: '386955907787',
    projectId: 'noorvia-3a12e',
    storageBucket: 'noorvia-3a12e.firebasestorage.app',
    iosClientId: '386955907787-60qcmr88pq6vshl63ha54hq6ss0babm9.apps.googleusercontent.com',
    iosBundleId: 'com.butterflydevs.noorvia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgfIGFdNM2tY-BEoq5GKuajNDg5iw44b8',
    appId: '1:386955907787:web:43f93aa8cb9a6a0353414e',
    messagingSenderId: '386955907787',
    projectId: 'noorvia-3a12e',
    authDomain: 'noorvia-3a12e.firebaseapp.com',
    storageBucket: 'noorvia-3a12e.firebasestorage.app',
    measurementId: 'G-Z7Y8YW30J5',
  );
}
